
export const GET_USER = 'redux/GET_USER';
export const GET_USER_REQUEST = 'redux/GET_USER_REQUEST';
export const GET_USER_REQUEST_SUCCESS = 'redux/GET_USER_REQUEST_SUCCESS';
export const GET_USER_REQUEST_FAILURE = 'redux/GET_USER_REQUEST_FAILURE';
export const GET_USER_REQUEST_END = 'redux/GET_USER_REQUEST_END';

